export type Owned = {
  id: string;
  species: string;
  level: number;
  xp: number;
  shards: number;
  upgrade: number;
  locked: boolean;
};
export type Profile = {
  id: string;
  name: string;
  avatar: number;
  version: number;
  level: number;
  xp: number;
  gold: number;
  diamonds: number;
  tokens: number;
  owned: Owned[];
  team: string[];
  pity: { as: number; s: number };
  quests: Record<string, number>;
  claims: string[];
  daily: {
    date: string;
    wins: number;
    train: number;
    resources: number;
    claimed: boolean;
  };
  ratings: { power: number; tactical: number };
  ranked: { power: number; tactical: number };
  wins: number;
  region: string;
  resources: string[];
  bond?: { species: string; chance: number; used: boolean };
  bosses: string[];
};
export type Status = { kind: string; turns: number; value: number; source?: string };
export type Unit = {
  id: string;
  species: string;
  side: number;
  slot: number;
  level: number;
  hp: number;
  maxHp: number;
  attack: number;
  defense: number;
  speed: number;
  shield: number;
  statuses: Status[];
  cooldowns: number[];
  revived: boolean;
  controlledLast: boolean;
  bank: number;
};
export type BattleEvent = {
  id: number;
  actor: string;
  target: string;
  action: string;
  name: string;
  amounts: { id: string; amount: number; shield: number }[];
  duration: number;
  at: number;
  message: string;
};
export type Battle = {
  id: string;
  units: Unit[];
  round: number;
  queue: string[];
  energy: number[];
  seed: number;
  event: BattleEvent | null;
  sequence: number;
  winner: number | null;
  log: string[];
  readyAt: number;
  deadline: number;
  delayed: { actor: string; target: string; action: number; round: number }[];
  mode: string;
};
