import {byId} from '../../../packages/shared/content';
export type Settings={master:number;music:number;sfx:number;ambience:number;voices:number;mute:boolean;reduced:boolean;shake:boolean;quality:string};
export const defaults:Settings={master:.6,music:.45,sfx:.65,ambience:.35,voices:.5,mute:false,reduced:false,shake:false,quality:'Medium'};
export const settings:Settings={...defaults,...JSON.parse(localStorage.getItem('mythoveya-settings')||'{}')};
export const MUSIC={title:{bpm:76,root:50,wave:'sine',pattern:[0,7,12,14,12,7,3,7]},haven:{bpm:88,root:55,wave:'triangle',pattern:[0,4,7,11,7,4,2,7]},meadow:{bpm:96,root:57,wave:'sine',pattern:[0,7,9,12,9,7,4,2]},canyon:{bpm:108,root:45,wave:'triangle',pattern:[0,0,7,3,5,7,10,7]},hollow:{bpm:72,root:54,wave:'sine',pattern:[0,12,7,14,3,10,7,12]},battle:{bpm:120,root:48,wave:'triangle',pattern:[0,7,3,7,5,12,10,7]},arena:{bpm:128,root:50,wave:'triangle',pattern:[0,3,7,10,7,12,5,7]},boss:{bpm:100,root:43,wave:'triangle',pattern:[0,1,7,3,0,10,7,1]}} as const;
// [oscillator, initial Hz, end Hz, seconds, noise blend, note intervals]
type Cue=[OscillatorType,number,number,number,number,number[]];
export const CUES:Record<string,Cue>={focus:['sine',520,680,.07,0,[]],confirm:['triangle',440,660,.18,0,[0,7]],back:['sine',420,230,.17,0,[]],error:['triangle',180,140,.2,.03,[0,1]],grass:['triangle',110,50,.09,.7,[]],stoneStep:['sine',170,65,.075,.35,[]],snowStep:['sine',220,90,.12,.8,[]],interact:['sine',420,630,.3,0,[0,4,7]],collect:['triangle',660,990,.24,.03,[0,7,12]],quest:['sine',440,880,.65,0,[0,4,7,12]],charge:['triangle',120,480,.7,.12,[0,7]],reveal:['sine',330,660,.8,.04,[0,4,7,12,16]],swing:['sine',240,90,.18,.65,[]],hit:['triangle',110,40,.15,.5,[]],launch:['triangle',350,800,.22,.18,[]],impact:['sine',90,35,.3,.65,[]],shield:['sine',260,520,.5,.03,[0,7,12]],break:['triangle',360,80,.28,.7,[]],heal:['sine',440,740,.6,.02,[0,4,9]],critical:['triangle',180,460,.35,.22,[0,7]],status:['sine',320,170,.35,.1,[0,3]],defeat:['triangle',220,55,.8,.2,[0,-5,-12]],flame:['triangle',90,280,.5,.75,[]],tide:['sine',340,90,.6,.55,[0,7]],grove:['triangle',240,480,.5,.35,[0,4,9]],stone:['triangle',85,32,.35,.8,[]],storm:['sine',110,55,.45,.8,[0,12]],frost:['sine',960,540,.5,.15,[0,7,12]],light:['sine',523,784,.7,0,[0,4,7,12]],shadow:['triangle',120,60,.7,.15,[0,1,7]],victory:['triangle',392,784,1.5,0,[0,4,7,12,16]],level:['sine',440,880,.9,0,[0,2,7,12]],rare:['sine',330,990,1.7,.06,[0,7,12,16,19]],pet:['sine',520,740,.3,.02,[0,4]],wind:['sine',120,160,2,.9,[]],leaves:['sine',600,300,1.2,.8,[]],chime:['sine',880,760,1.4,.02,[0,7]]};
class AudioEngine{
 ctx?:AudioContext;master?:GainNode;buses:Record<string,GainNode>={};voices=0;scene='';timer?:ReturnType<typeof setInterval>;beat=0;next=0;last=new Map<string,number>();musicGain?:GainNode;ambientBeat=0;
 async unlock(){if(!this.ctx){this.ctx=new AudioContext();this.master=this.ctx.createGain();const limiter=this.ctx.createDynamicsCompressor();limiter.threshold.value=-16;limiter.ratio.value=5;this.master.connect(limiter).connect(this.ctx.destination);for(const bus of ['music','sfx','ambience','voices']){this.buses[bus]=this.ctx.createGain();this.buses[bus].connect(this.master);}this.update();document.addEventListener('visibilitychange',()=>{if(document.hidden)this.ctx?.suspend();else this.ctx?.resume();});this.timer=setInterval(()=>this.schedule(),100);}await this.ctx.resume();}
 update(){localStorage.setItem('mythoveya-settings',JSON.stringify(settings));if(!this.ctx||!this.master)return;this.master.gain.setTargetAtTime(settings.mute?0:settings.master,this.ctx.currentTime,.05);for(const k of ['music','sfx','ambience','voices'] as const)this.buses[k].gain.setTargetAtTime(settings[k],this.ctx.currentTime,.08);}
 tone(freq:number,end:number,duration:number,wave:OscillatorType,gain:number,bus:string,when?:number,pan=0){if(!this.ctx||this.voices>=40||document.hidden)return;const c=this.ctx,t=when??c.currentTime,o=c.createOscillator(),v=c.createGain(),p=c.createStereoPanner();o.type=wave;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(25,end),t+duration);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),t+.025);v.gain.exponentialRampToValueAtTime(.0001,t+duration);p.pan.value=Math.max(-.8,Math.min(.8,pan));o.connect(v).connect(p).connect(bus==='music'&&this.musicGain?this.musicGain:this.buses[bus]);o.start(t);o.stop(t+duration+.02);this.voices++;o.onended=()=>{o.disconnect();v.disconnect();p.disconnect();this.voices--;};}
 noise(duration:number,gain:number,bus:string,cutoff=800){if(!this.ctx||this.voices>=40)return;const c=this.ctx,len=Math.floor(c.sampleRate*duration),buffer=c.createBuffer(1,len,c.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1)*(1-i/len);const src=c.createBufferSource(),filter=c.createBiquadFilter(),v=c.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.value=cutoff;v.gain.value=gain;src.connect(filter).connect(v).connect(this.buses[bus]);src.start();this.voices++;src.onended=()=>{src.disconnect();filter.disconnect();v.disconnect();this.voices--;};}
 cue(name:string,pan=0,bus='sfx'){const cue=CUES[name]||CUES.confirm;if(!this.ctx||Date.now()-(this.last.get(name)||0)<65)return;this.last.set(name,Date.now());const [wave,f,e,d,n,notes]=cue;this.tone(f,e,d,wave,.09,bus,undefined,pan);notes.forEach((x,i)=>this.tone(f*2**(x/12),f*2**(x/12),d*.65,wave,.045,bus,this.ctx!.currentTime+i*.09,pan));if(n)this.noise(d,.09*n,bus,name==='frost'?2400:850);if(['rare','victory','defeat','quest'].includes(name)){this.buses.music.gain.setTargetAtTime(settings.music*.3,this.ctx.currentTime,.1);this.buses.music.gain.setTargetAtTime(settings.music,this.ctx.currentTime+d,.4);}}
 voice(id:string,kind='call',pan=0){const s=byId[id];if(!s||!this.ctx)return;const f=180+(5-Math.floor(s.index/10))*65+(s.index%10)*12;const factors:Record<string,number>={insect:1.7,bird:2,amphibian:.8,fox:1.1,quadruped:.95,shell:.6,serpent:.7,aquatic:.85,spirit:1.4,golem:.28,dragon:.45,antler:.9};const base=f*(factors[s.family]||1);this.tone(base,base*(kind==='hurt'?.7:kind==='attack'?1.35:1.15),.25+s.variant*.04,s.index%3?'sine':'triangle',.12,'voices',undefined,pan);if(['dragon','golem','shell'].includes(s.family))this.noise(.32,.08,'voices',350);}
 location(scene:string){if(this.scene===scene)return;this.scene=scene;this.beat=0;this.next=this.ctx?.currentTime||0;if(this.ctx){const old=this.musicGain;old?.gain.setTargetAtTime(0,this.ctx.currentTime,.5);if(old)setTimeout(()=>old.disconnect(),2500);this.musicGain=this.ctx.createGain();this.musicGain.gain.value=0;this.musicGain.connect(this.buses.music);this.musicGain.gain.setTargetAtTime(1,this.ctx.currentTime,.8);}}
 schedule(){if(!this.ctx||this.ctx.state!=='running')return;const song=MUSIC[this.scene as keyof typeof MUSIC]||MUSIC.title;const step=60/song.bpm/2;if(this.next<this.ctx.currentTime-.2)this.next=this.ctx.currentTime;while(this.next<this.ctx.currentTime+.2){const bar=Math.floor(this.beat/8)%16,chord=[0,5,3,7][Math.floor(bar/4)],note=song.pattern[this.beat%8]+song.root+chord;const hz=440*2**((note-69)/12);if(this.beat%2===0||this.scene==='battle'||this.scene==='arena')this.tone(hz,hz,step*2.8,song.wave,.04,'music',this.next);if(this.beat%8===0){for(const n of [0,7,12]){const f=440*2**((song.root+chord-12+n-69)/12);this.tone(f,f,step*7,'sine',.035,'music',this.next);}}if(this.beat%4===0&&['battle','boss','arena','canyon'].includes(this.scene))this.tone(70,35,.18,'sine',.06,'music',this.next);this.next+=step;this.beat=(this.beat+1)%128;}
 if(++this.ambientBeat%45===0&&['haven','meadow','canyon','hollow'].includes(this.scene))this.cue(this.scene==='hollow'?'chime':this.scene==='canyon'?'wind':'leaves',0,'ambience');}
}
export const audio=new AudioEngine();
