import {describe,it,expect} from 'vitest';
import {SPECIES,byId} from '../packages/shared/content';
import {act,makeBattle,targets,stats,autoAction} from '../packages/shared/combat';
import {MUSIC,CUES} from '../packages/shared/audio-content';
const owned=(species:string)=>({id:species,species,level:1,xp:0,shards:0,upgrade:0,locked:false});
function fixture(id:string){const a=[owned(id),...SPECIES.slice(0,5).map(s=>owned(s.id))];const b=makeBattle(id,[a,SPECIES.slice(10,16).map(s=>owned(s.id))]);b.queue=['0:0',...b.queue.filter(x=>x!=='0:0')];b.energy=[10,10];return b;}
describe('signature behavior and presentation contracts',()=>{
 it('keeps attack bonuses on the attacker and revival never damages its owner',()=>{for(const id of ['zippinch','raijora','ignivara']){const b=fixture(id);const hp=b.units[0].hp;act(b,0,1,'1:0',0);expect(b.units[0].hp).toBe(hp);expect(b.units[6].statuses.some(s=>['haste','boost','rebirth'].includes(s.kind))).toBe(false);}const b=fixture('ignivara');act(b,0,1,'1:0',0);expect(b.units[0].statuses.some(s=>s.kind==='rebirth')).toBe(true);});
 it('shields allies while slowing enemies',()=>{const b=fixture('crysalune');act(b,0,1,'0:0',0);expect(b.units.filter(u=>u.side===0).every(u=>u.shield>0&&!u.statuses.some(s=>s.kind==='slow'))).toBe(true);expect(b.units.filter(u=>u.side===1).every(u=>u.statuses.some(s=>s.kind==='slow'))).toBe(true);});
 it('heals exactly two with Healing Current and targets proper rows',()=>{const b=fixture('ripplefin');b.units.filter(u=>u.side===0).forEach(u=>u.hp-=50);const hp=b.units.map(u=>u.hp);act(b,0,1,'0:0',0);expect(b.units.filter((u,i)=>u.hp>hp[i])).toHaveLength(2);const f=fixture('frostwhisk');act(f,0,1,'0:0',0);expect(f.units.filter(u=>u.side===0&&u.slot>=3).every(u=>u.shield>0)).toBe(true);expect(f.units.filter(u=>u.side===0&&u.slot<3).every(u=>u.shield===0||byId[u.species].passive.effect==='shield')).toBe(true);});
 it('limits resurrection to one target and one lifetime per match',()=>{const b=fixture('aurelith');b.units[1].hp=0;b.units[2].hp=0;act(b,0,2,'0:1',0);expect(b.units[1].hp).toBeGreaterThan(0);expect(b.units[2].hp).toBe(0);b.units[1].hp=0;expect(targets(b,b.units[0],2).some(u=>u.id==='0:1')).toBe(false);});
 it('normalizes tactical rarity and upgrades by role',()=>{const low=stats(owned('cindermite'),true);const high=stats({...owned('solkarath'),level:30,upgrade:5},true);expect(Math.abs(low.attack-high.attack)).toBeLessThanOrEqual(1);expect(Math.abs(low.hp-high.hp)).toBeLessThanOrEqual(1);expect(stats({...owned('solkarath'),level:30,upgrade:5}).hp).toBeGreaterThan(high.hp);});
 it('advances each living actor only once within a round',()=>{const b=fixture('nimbuskit');const seen=new Set<string>();while(b.round===1&&b.winner===null){const id=b.queue[0];expect(seen.has(id)).toBe(false);seen.add(id);const choice=autoAction(b);act(b,b.units.find(u=>u.id===id)!.side,choice.action,choice.target,0);}expect(seen.size).toBeLessThanOrEqual(12);});
 it('provides eight full music cycles and more than thirty distinct cue recipes',()=>{expect(Object.keys(MUSIC)).toHaveLength(8);for(const song of Object.values(MUSIC)){expect(song.steps*60/song.bpm/2).toBeGreaterThanOrEqual(45);expect(song.steps*60/song.bpm/2).toBeLessThanOrEqual(90);}expect(new Set(Object.values(CUES).map(c=>JSON.stringify(c))).size).toBeGreaterThanOrEqual(30);});
});
