import {Room,Client} from '@colyseus/core';
import {z} from 'zod';
import {randomInt} from 'node:crypto';
import {act,autoAction,elo,makeBattle} from '../../packages/shared/combat';
import type {Battle} from '../../packages/shared/types';
import {atomic,authenticate,db,getProfile,save} from './store';
import {activeHuman,pve,team} from './game';
export class ArenaRoom extends Room {
 maxClients=2;players:{session:string;id:string;name:string;ready:boolean;missed:number}[]=[];battle:Battle|null=null;mode:'power'|'tactical'='tactical';ranked=false;settled=false;last=new Map<string,number>();
 onCreate(options:any){this.mode=options.mode==='power'?'power':'tactical';this.ranked=options.ranked===true;this.setPrivate(!this.ranked);this.onMessage('ready',(c)=>{const p=this.players.find(p=>p.session===c.sessionId);if(p&&!this.battle){p.ready=true;if(this.players.length===2&&this.players.every(p=>p.ready)){this.battle=makeBattle(this.roomId,this.players.map(p=>team(getProfile(p.id))),this.mode,randomInt(0,1000000));this.battle.deadline=Date.now()+20000;}this.sync();}});this.onMessage('action',(c,data)=>{try{if(Date.now()-(this.last.get(c.sessionId)||0)<100)throw Error('Please wait.');this.last.set(c.sessionId,Date.now());const v=z.object({action:z.number().int().min(0).max(2),target:z.string().max(10),sequence:z.number().int()}).parse(data);const side=this.players.findIndex(p=>p.session===c.sessionId);if(!this.battle||this.battle.sequence!==v.sequence||Date.now()<this.battle.readyAt)throw Error('Wait for your turn.');act(this.battle,side,v.action,v.target);this.players[side].missed=0;this.finish();this.sync();}catch(e){c.send('error',(e as Error).message);}});this.onMessage('sync',()=>this.sync());this.onMessage('forfeit',c=>{if(this.battle&&this.battle.winner===null){this.battle.winner=1-this.players.findIndex(p=>p.session===c.sessionId);this.finish();this.sync();}});this.setSimulationInterval(()=>this.tick(),200);}
 onAuth(_c:Client,options:any){const p=authenticate(z.string().length(64).parse(options.token));team(p);if(activeHuman.has(p.id)||pve.get(p.id)?.winner===null)throw Error('Finish your current match first.');return {id:p.id,name:p.name};}
 onJoin(c:Client,_o:any,auth:{id:string;name:string}){if(this.players.some(p=>p.id===auth.id))throw Error('Use a different browser profile for your opponent.');activeHuman.add(auth.id);this.players.push({session:c.sessionId,id:auth.id,name:auth.name,ready:false,missed:0});this.sync();}
 async onLeave(c:Client,consented:boolean){const player=this.players.find(p=>p.session===c.sessionId);if(!player)return;if(this.battle&&this.battle.winner===null&&!consented){try{await this.allowReconnection(c,30);this.sync();return;}catch{}}if(this.battle&&this.battle.winner===null){this.battle.winner=1-this.players.indexOf(player);this.finish();}else if(!this.battle)this.players=this.players.filter(p=>p!==player);activeHuman.delete(player.id);this.sync();}
 onDispose(){for(const p of this.players)activeHuman.delete(p.id);}
 tick(){const b=this.battle;if(!b||b.winner!==null||Date.now()<b.deadline)return;const actor=b.units.find(u=>u.id===b.queue[0])!;const p=this.players[actor.side];if(++p.missed>=3)b.winner=1-actor.side;else{const t=autoAction({...b,energy:[0,0]});act(b,actor.side,0,t.target);}this.finish();this.sync();}
 finish(){const b=this.battle;if(!b||b.winner===null||this.settled)return;atomic(()=>{if(db.prepare('SELECT id FROM matches WHERE id=?').get(b.id))return;const ps=this.players.map(p=>getProfile(p.id));if(this.ranked){const ratings=elo(ps[0].ratings[this.mode],ps[1].ratings[this.mode],b.winner===2?.5:b.winner===0?1:0);ps.forEach((p,i)=>{p.ratings[this.mode]=ratings[i];p.ranked[this.mode]++;if(p.ranked[this.mode]%3===0)p.diamonds+=50;});}for(const p of ps){p.quests.arena=1;save(p);}db.prepare('INSERT INTO matches VALUES(?,?)').run(b.id,JSON.stringify({winner:b.winner,ranked:this.ranked,mode:this.mode,players:ps.map(p=>p.id),ratings:ps.map(p=>p.ratings[this.mode])}));});this.settled=true;for(const p of this.players)activeHuman.delete(p.id);}
 sync(){this.broadcast('snapshot',{code:this.roomId,players:this.players.map(({id,name,ready})=>({id,name,ready})),battle:this.battle,mode:this.mode,ranked:this.ranked});}
}
